# Site settings
title: Edviges Fernandes
description: 'Me, Edviges, by definition I am a Battlewoman. Going to battle via my blog'
url: 'https://edviges.github.io'
baseurl: '/'
google_analytics: 'UA-84322036-1'
disqus_shortname: 'edviges-github-io.disqus.com'

author:
  name: 'Edviges Fernandes'
  email: edviges29@gmail.com
  twitter_username: slaaysrcecoders
  facebook_username: slaaysourcecoders
  github_username:  edviges
  linkedin_username:  edviges-fernandes-794a3991

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
